[seo]
enabled = true
domain = "https://nebulaproxy.io"

[db]
name = "nebula_prod_db"
username = "nebula_admin"
password = "StrongSecureP@ssw0rd!" # Change this to your actual secure password
postgres = true

[postgres]
domain = "127.0.0.1" # or your actual PostgreSQL server IP/domain
port = 5432

[server.server]
port = 8080
wisp = true
logging = true

[masqr]
enabled = true
failed = "failed.html"
whitelisted = ["https://services.org"]
url = "https://license.nebulaservices.org/validate
